# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6841058805015a82587c134c533b50de2805951cb63530aa1241d613e1e1d4ab7ee839efb676f76a1398282d18d43bb23f0f66ab839f0d2463272afa2ed4d69

test:
  secret_key_base: a72b4c62169608e1d96167ac53e335c91aef7779e31cc7948da8b2f1028bc1fcee37e976f1065bb6cd624476a25453c64903f64280d35dcead08bc19927fc0a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
